version: '3'

services:
  go:
    image: fhw240579805/chat-backend:v1.1.0
    restart: always
    links:
      - mysql
    volumes:
      - /home/chat/static:/dist/statics
    ports:
      - 9998:9998
    networks:
      - my-bridge

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - my-bridge

volumes:
  mysql-data:

networks:
  my-bridge:
    driver: bridge